### ISSUE TITLE
register and code minification

### ISSUE THREAD

**Issue by donpark** [github/catalyst#98]
Ran into this with `esbuild` minified custom element. Names of classes exported from per-element files are not preserved after `esbuild` minification. While the problem may be overly eager minification, it'd be nice of custom element name could be optionally specified. Something like `@controller('my-component')`.

<img width="968" alt="Screen Shot 2020-12-29 at 6 09 28 AM" src="https://user-images.githubusercontent.com/127594/103289610-787b3b80-499c-11eb-854b-f94f8173d93c.png">

**Comment by keithamus** [comment]
Thanks for the issue @donpark 

You'll need to either exclude all class names from being minified in your build, or alternatively a subset with a RegExp. For GitHub we allow any classname ending in `Element` to go through our build unminified, meaning Catalyst is able to pick them up properly. 

During the API design we considered passing the name to `@controller`; e.g. `@controller('FooBarElement') class FooBarElement...` but we dislike the ergonomics of having to express a name twice. Ultimately we decided to simply disallow minification of classnames in our builds - perhaps it is worth documenting this in the guide.

**Comment by Scipion** [comment]
Hi @keithamus

What about set the name in the controller as in `@controller('FooBarElement')` just optionally keeping the current behaviour?.
IMHO the mechanism of removing "Element" and take the rest as the custom element name is very elegant, but I like the idea of being able to change it that @donpark proposes not only to fix the minification (btw I also had problems with parcel-bundler in that way) also as a feature.

I started a POC to add this feature and keep the already working syntax, so both `@controller class FooBarElement` and `@controller('FooBarElement') class RandomName` work.

https://github.com/Scipion/catalyst/commit/0285abd93fa2c1420f6c0171a2d39ee72ae07239

Does it matches the original API design?

**Comment by donpark** [comment]
> What about set the name in the controller as in `@controller('FooBarElement')` just optionally keeping the current behaviour?.

This commit in my fork also does that, optional explicit naming. https://github.com/donpark/catalyst/commit/110426b62ed0541fb354fe5bf82a601764b4a916

I did run into an issue with `@controller` implementation calling `register()` which handles the actual class name derived naming. That conflicts with the way TypeScript decorator factory works so I had to break out `register()` logic to `_register()` function so it can be called from `controller()`.

Designwise, current Catalyst convention of allowing its decorators to also be directly callable limits adding optional arguments to the decorators in the future.

**Comment by keithamus** [comment]
Thanks for this active discussion, it's all very good to see!

> Designwise, current Catalyst convention of allowing its decorators to also be directly callable is unfortunate...

This is an intentional design choice, as we want to keep them ergonomically simple. Adding arguments adds utility but it also adds combinatorial complexity; it comes at a cost. Every time we've looked at adding arguments we've concluded it is a complexity not worth the cost, in our opinion. We sort of allude to this in the Guide (although we could do better at calling it out explicitly): https://github.github.io/catalyst/guide/decorators/#function-calling-decorators.

On the surface, keeping class names unminified might seem like a bad idea but we've really come to appreciate the simplicity. It aids in debugging (error stacks reflect the unminified class name), and it doesn't have a detrimental effect on the output. Here's a demonstration using [`Terser`](https://terser.org/docs/cli-usage):
 
```js
// Minified output using `@controller('FooBarElement') and an anonymous class`. gzipped: 94 bytes
let e=class extends HTMLElement{};e=__decorate([controller("FooBarElement")],e)

// Minified  output using `@controller; class FooBarElement` with `--keep-classnames`. gzipped: 90 bytes.
let e=class FooBarElement extends HTMLElement{};e=__decorate([controller],e);
```

Clearly this example is very contrived but it demonstrates the point that there's little to gain from compressing classnames here if you're already expressing them in a string.

Again, Terser allows you to specify to keep either all class names, or just the ones matching a certain pattern. One problem I can see is that `esbuild` only has a `--keep-names` flag which keeps function names as well as classes. Perhaps this is something you could file upstream with them?

--

Right now, I think I'm going to close _this_ issue as a design choice we're aware of, but are happy with the current trade-offs. Shipping unminified class names works well for us, and we believe it will work well for others with the correct tooling. The solutions to work around minifying class names adds extra ergonomic burden to developers which is remediated with tooling, and to us this isn't a worthwhile trade-off.

Although I'm closing this issue, I'm happy to keep discussing further and we can always re-open later if we find a strategy which works better than the one we have now.
